-- DEAL DESK: PE-specific tables (additive only — no DealDesk tables modified).
-- This migration was generated by drizzle-kit, then manually pruned to remove
-- statements that drift against pre-existing DealDesk migrations (unrelated
-- to the DealDesk fork). Only dd_* objects remain.

CREATE TYPE "public"."dd_email_status" AS ENUM('unverified', 'verified', 'bounced', 'invalid');--> statement-breakpoint
CREATE TYPE "public"."dd_outreach_send_status" AS ENUM('queued', 'awaiting_approval', 'sent', 'replied', 'bounced', 'unsubscribed', 'failed');--> statement-breakpoint
CREATE TYPE "public"."dd_suppression_reason" AS ENUM('unsubscribed', 'bounced', 'manual', 'replied_not_interested');--> statement-breakpoint
CREATE TYPE "public"."dd_target_status" AS ENUM('sourced', 'qualified', 'contacted', 'replied', 'meeting_booked', 'in_diligence', 'passed', 'closed_won', 'closed_lost');--> statement-breakpoint
CREATE TYPE "public"."dd_thesis_status" AS ENUM('active', 'paused', 'archived');--> statement-breakpoint
CREATE TABLE "dd_theses" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"deal_desk_company_id" uuid NOT NULL,
	"name" varchar(255) NOT NULL,
	"sector" varchar(255) NOT NULL,
	"sub_sectors" jsonb DEFAULT '[]'::jsonb NOT NULL,
	"geos" jsonb DEFAULT '[]'::jsonb NOT NULL,
	"revenue_min" numeric(15, 2),
	"revenue_max" numeric(15, 2),
	"ebitda_min" numeric(15, 2),
	"ebitda_max" numeric(15, 2),
	"deal_size_min" numeric(15, 2),
	"deal_size_max" numeric(15, 2),
	"ownership_preferences" jsonb DEFAULT '[]'::jsonb NOT NULL,
	"exclusion_criteria" text,
	"narrative" text,
	"status" "dd_thesis_status" DEFAULT 'active' NOT NULL,
	"template_slug" varchar(255),
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE "dd_targets" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"deal_desk_company_id" uuid NOT NULL,
	"thesis_id" uuid NOT NULL,
	"sourced_by_agent_id" uuid,
	"source_ticket_id" uuid,
	"company_name" varchar(255) NOT NULL,
	"website" varchar(2048),
	"description" text,
	"sector" varchar(255),
	"sub_sector" varchar(255),
	"hq_city" varchar(255),
	"hq_state" varchar(100),
	"hq_country" varchar(100) DEFAULT 'US' NOT NULL,
	"estimated_revenue" numeric(15, 2),
	"estimated_ebitda" numeric(15, 2),
	"estimated_employees" integer,
	"ownership_type" varchar(100),
	"fit_score" integer,
	"fit_rationale" text,
	"sources" jsonb DEFAULT '[]'::jsonb NOT NULL,
	"status" "dd_target_status" DEFAULT 'sourced' NOT NULL,
	"tags" jsonb DEFAULT '[]'::jsonb NOT NULL,
	"notes" text,
	"crm_external_id" varchar(255),
	"status_changed_at" timestamp with time zone,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE "dd_intermediaries" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"deal_desk_company_id" uuid NOT NULL,
	"name" varchar(255) NOT NULL,
	"firm" varchar(255),
	"title" varchar(255),
	"coverage_sectors" jsonb DEFAULT '[]'::jsonb NOT NULL,
	"coverage_size_min" numeric(15, 2),
	"coverage_size_max" numeric(15, 2),
	"email" varchar(255),
	"linkedin_url" varchar(2048),
	"phone" varchar(50),
	"recent_deals" jsonb DEFAULT '[]'::jsonb NOT NULL,
	"last_touch_date" date,
	"cadence_days" integer DEFAULT 60 NOT NULL,
	"next_touch_due" date,
	"relationship_strength" integer DEFAULT 1 NOT NULL,
	"notes" text,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE "dd_contacts" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"target_id" uuid NOT NULL,
	"deal_desk_company_id" uuid NOT NULL,
	"first_name" varchar(255) NOT NULL,
	"last_name" varchar(255),
	"title" varchar(255),
	"email" varchar(255),
	"email_status" "dd_email_status" DEFAULT 'unverified' NOT NULL,
	"linkedin_url" varchar(2048),
	"phone" varchar(50),
	"enriched_by_agent_id" uuid,
	"enriched_at" timestamp with time zone,
	"source" varchar(100),
	"is_primary" boolean DEFAULT false NOT NULL,
	"notes" text,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE "dd_outreach_campaigns" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"deal_desk_company_id" uuid NOT NULL,
	"thesis_id" uuid,
	"name" varchar(255) NOT NULL,
	"cadence_steps" jsonb DEFAULT '[]'::jsonb NOT NULL,
	"daily_send_cap" integer DEFAULT 30 NOT NULL,
	"approval_mode" boolean DEFAULT true NOT NULL,
	"from_mailbox_ref" varchar(255),
	"status" varchar(50) DEFAULT 'draft' NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE "dd_outreach_sends" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"deal_desk_company_id" uuid NOT NULL,
	"campaign_id" uuid NOT NULL,
	"target_id" uuid NOT NULL,
	"contact_id" uuid,
	"cadence_step" integer DEFAULT 0 NOT NULL,
	"subject" varchar(500) NOT NULL,
	"body" text NOT NULL,
	"status" "dd_outreach_send_status" DEFAULT 'queued' NOT NULL,
	"drafted_by_agent_id" uuid,
	"approved_by_user_id" uuid,
	"approved_at" timestamp with time zone,
	"scheduled_send_at" timestamp with time zone,
	"sent_at" timestamp with time zone,
	"replied_at" timestamp with time zone,
	"external_message_id" varchar(500),
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE "dd_suppression_list" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"deal_desk_company_id" uuid NOT NULL,
	"email_or_domain" varchar(255) NOT NULL,
	"reason" "dd_suppression_reason" NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE "dd_memos" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"deal_desk_company_id" uuid NOT NULL,
	"generated_by_agent_id" uuid,
	"week_start_date" date NOT NULL,
	"markdown" text NOT NULL,
	"metrics_snapshot" jsonb DEFAULT '{}'::jsonb NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE "dd_role_templates" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"slug" varchar(255) NOT NULL,
	"name" varchar(255) NOT NULL,
	"description" text NOT NULL,
	"default_heartbeat_cron" varchar(100) NOT NULL,
	"default_budget_usd" integer DEFAULT 50 NOT NULL,
	"skill_files" jsonb DEFAULT '[]'::jsonb NOT NULL,
	"system_prompt" text NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint
ALTER TABLE "dd_contacts" ADD CONSTRAINT "dd_contacts_target_id_dd_targets_id_fk" FOREIGN KEY ("target_id") REFERENCES "public"."dd_targets"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "dd_outreach_campaigns" ADD CONSTRAINT "dd_outreach_campaigns_thesis_id_dd_theses_id_fk" FOREIGN KEY ("thesis_id") REFERENCES "public"."dd_theses"("id") ON DELETE set null ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "dd_outreach_sends" ADD CONSTRAINT "dd_outreach_sends_campaign_id_dd_outreach_campaigns_id_fk" FOREIGN KEY ("campaign_id") REFERENCES "public"."dd_outreach_campaigns"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "dd_outreach_sends" ADD CONSTRAINT "dd_outreach_sends_target_id_dd_targets_id_fk" FOREIGN KEY ("target_id") REFERENCES "public"."dd_targets"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "dd_outreach_sends" ADD CONSTRAINT "dd_outreach_sends_contact_id_dd_contacts_id_fk" FOREIGN KEY ("contact_id") REFERENCES "public"."dd_contacts"("id") ON DELETE set null ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "dd_targets" ADD CONSTRAINT "dd_targets_thesis_id_dd_theses_id_fk" FOREIGN KEY ("thesis_id") REFERENCES "public"."dd_theses"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
CREATE INDEX "dd_contacts_target_id_idx" ON "dd_contacts" USING btree ("target_id");--> statement-breakpoint
CREATE INDEX "dd_contacts_company_id_idx" ON "dd_contacts" USING btree ("deal_desk_company_id");--> statement-breakpoint
CREATE INDEX "dd_intermediaries_company_id_idx" ON "dd_intermediaries" USING btree ("deal_desk_company_id");--> statement-breakpoint
CREATE INDEX "dd_intermediaries_next_touch_due_idx" ON "dd_intermediaries" USING btree ("next_touch_due");--> statement-breakpoint
CREATE INDEX "dd_memos_company_id_idx" ON "dd_memos" USING btree ("deal_desk_company_id");--> statement-breakpoint
CREATE UNIQUE INDEX "dd_memos_company_week_idx" ON "dd_memos" USING btree ("deal_desk_company_id","week_start_date");--> statement-breakpoint
CREATE INDEX "dd_outreach_campaigns_company_id_idx" ON "dd_outreach_campaigns" USING btree ("deal_desk_company_id");--> statement-breakpoint
CREATE INDEX "dd_outreach_sends_company_id_idx" ON "dd_outreach_sends" USING btree ("deal_desk_company_id");--> statement-breakpoint
CREATE INDEX "dd_outreach_sends_campaign_id_idx" ON "dd_outreach_sends" USING btree ("campaign_id");--> statement-breakpoint
CREATE INDEX "dd_outreach_sends_status_idx" ON "dd_outreach_sends" USING btree ("status");--> statement-breakpoint
CREATE UNIQUE INDEX "dd_outreach_sends_campaign_contact_step_idx" ON "dd_outreach_sends" USING btree ("campaign_id","contact_id","cadence_step");--> statement-breakpoint
CREATE UNIQUE INDEX "dd_role_templates_slug_idx" ON "dd_role_templates" USING btree ("slug");--> statement-breakpoint
CREATE UNIQUE INDEX "dd_suppression_list_company_email_idx" ON "dd_suppression_list" USING btree ("deal_desk_company_id","email_or_domain");--> statement-breakpoint
CREATE INDEX "dd_targets_company_id_idx" ON "dd_targets" USING btree ("deal_desk_company_id");--> statement-breakpoint
CREATE INDEX "dd_targets_thesis_id_idx" ON "dd_targets" USING btree ("thesis_id");--> statement-breakpoint
CREATE INDEX "dd_targets_status_idx" ON "dd_targets" USING btree ("status");--> statement-breakpoint
CREATE INDEX "dd_targets_fit_score_idx" ON "dd_targets" USING btree ("fit_score");--> statement-breakpoint
CREATE UNIQUE INDEX "dd_targets_company_name_idx" ON "dd_targets" USING btree ("deal_desk_company_id","company_name");--> statement-breakpoint
CREATE INDEX "dd_theses_company_id_idx" ON "dd_theses" USING btree ("deal_desk_company_id");--> statement-breakpoint
CREATE INDEX "dd_theses_status_idx" ON "dd_theses" USING btree ("status");
